### ISSUE TITLE
`warning: Could not find remote branch 0.0.8 to clone.` when trying `brew install asyncs/brew/asyncy`

### ISSUE THREAD

**Issue by muhh** [asyncy/homebrew-brew#1]
https://github.com/asyncy/homebrew-brew/blob/95ff390d95fdaec77106e7d79f4679118b6c13be/Formula/asyncy.rb#L6 defines tag 0.0.8, but this tag can't be found in https://github.com/asyncy/cli

**Comment by stevepeak** [comment]
@muhh Thank you pointing this out. We are not quite ready for release yet. The plan is by months end. However, you'll still need to be invited into Alpha/Beta:  https://asyncy.click/beta-invite

Hope to see you join 😄

**Comment by judepereira** [comment]
Resolved by taking away ptyprocess which doesn't compile half the time from Storyscript. See https://github.com/storyscript/storyscript/issues/532.
